apply plugin: "com.diffplug.spotless"

spotless {
    java {
        target 'src/**/*.java'
        googleJavaFormat().aosp()
        removeUnusedImports()
        trimTrailingWhitespace()
        leadingTabsToSpaces()
        endWithNewline()
    }

    kotlinGradle {
        target '*.gradle.kts', 'settings.gradle.kts'
        ktlint()
        trimTrailingWhitespace()
        endWithNewline()
    }

    kotlin {
        target 'src/**/*.kt'
        ktlint()
        trimTrailingWhitespace()
        leadingTabsToSpaces()
        endWithNewline()
    }

    format 'misc', {
        target '*.gradle', '*.md', '.gitignore', 'gradle/**/*.gradle'
        leadingTabsToSpaces()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
